### ISSUE TITLE
Support for Python 3.x

### ISSUE THREAD

**Issue by hdsouza** [ahartoto/lendingclub2#12]
Hi Alex, 
I noticed the earlier issue about support for 2.7 , although that was closed. 
That being said will the code be tested for a new version of python like 3.x?

Thanks
Hilario

**Comment by ahartoto** [comment]
Hi @hdsouza,

Python 3.x is supported:
https://github.com/ahartoto/lendingclub2/blob/05f5ecfa3b3cf3745b8256bed62bdda69355f381/setup.py#L37

Are you seeing any problem with the implementations?

**Comment by hdsouza** [comment]
Thanks Alex. I will check

**Comment by ahartoto** [comment]
I just released 0.5.0 to made it clear with fixes to the documentations.

**Comment by hdsouza** [comment]
Thanks Alex. I currently have been using Python 2.7 but now I need to start the testing with Python 3.7 and need some help.
I downloaded and installed  https://www.python.org/downloads/release/python-370/

Now before calling the Lending club modules, do i need to run:
python -m pip install virtualenv
python -m pip install pip --upgrade
python -m virtualenv env
pip install -r req.txt

**Comment by ahartoto** [comment]
Assuming that `python` executable here means Python 3.7 executable (and bash shell):
```sh
python -m venv /path/to/virtualenv/root
cd /path/to/virtualenv/root
. ./bin/activate
pip install --upgrade pip
pip install lendingclub2
```

For development you'd need to install from `requirements.txt` and `requirements-dev.txt`.

**Comment by ahartoto** [comment]
Latest released of Python 3.7 branch is [3.7.2](https://www.python.org/downloads/release/python-372/) (just in case you want to use latest).

**Comment by hdsouza** [comment]
Thanks Alex. I was able to get/load the Lending club module (I am running Python  on windows 10 via commandline)
But I get an error when getting the balance.
In the script below I also tried by replacing investor_id with LENDING_CLUB_INVESTOR_ID and api_key with LENDING_CLUB_API_KEY, but get the same error

Here is the script:
```
investor_id = "xxxxxx"
api_key = "xxxxxx"
import lendingclub2
from lendingclub2.account import InvestorAccount
account = InvestorAccount()
print(account.available_balance)
```

Error:
(env) C:\Python37\env\Scripts>python c:\temp\lc.py
Traceback (most recent call last):
  File "c:\temp\lc.py", line 12, in <module>
    account = InvestorAccount()
  File "C:\Python37\env\lib\site-packages\lendingclub2\account.py", line 33, in __init__
    self._summary = Summary(InvestorAccount.id())
  File "C:\Python37\env\lib\site-packages\lendingclub2\account.py", line 48, in id
    config = utils.get_config_content()
  File "C:\Python37\env\lib\site-packages\lendingclub2\utils.py", line 30, in get_config_content
    raise LCError(fstr)
lendingclub2.error.LCError: expected configuration path doesn't exist: C:\Users\E910327\.lendingclub

**Comment by ahartoto** [comment]
Oh. It doesn't use local variable that way. You'd have to:
```python
import os
from lendingclub2.config import API_KEY_ENV, INVESTOR_ID_ENV
from lendingclub2.account import InvestorAccount

os.environ[INVESTOR_ID_ENV] = 'xxxxx'
os.environ[API_KEY_ENV] = 'xxxxx'

account = InvestorAccount()
print(account.available_balance)
```

**Comment by hdsouza** [comment]
That worked great. Thanks Alex.
I noticed the reference to gillick and have been using his code (Python 2.7) for assigning Notes to portfolios.  [https://github.com/jgillick/LendingClub/blob/master/lendingclub/__init__.py](https://github.com/jgillick/LendingClub/blob/master/lendingclub/__init__.py)  (Look for assign_to_portfolio).
Does your code have something similar?
Thanks

**Comment by ahartoto** [comment]
Are you planning to add the notes to an existing portfolio or are you interested in creating a new one?

**Comment by hdsouza** [comment]
I want to assign Existing Notes to Existing Portfolios.
(I do not need the script to create new Portfolios).
The notes could be in an Existing portfolio or Newly purchased Notes (NULL Portfolio).
Here is how I would do it with the earlier code: 
`Assign_Notes = lc.assign_to_portfolio(portfolio_name, loan_id, order_id)`

**Comment by ahartoto** [comment]
Looking through the API documentation from LendingClub, it seems that we can only assign the notes to existing portfolios when we are submitting the order for the notes via [submit-orders](https://www.lendingclub.com/developers/submit-order) endpoint.

Iterating over the portfolios is something that we can already do:
```python
from lendingclub2.account import InvestorAccount

account = InvestorAccount()
for portfolio in account.portfolios:
    print(portfolio.id, portfolio.name)
```

**Comment by hdsouza** [comment]
Thanks Alex. We can do it for orders on the primary market.
but NOT for Notes purchased on the secondary market.
Also more importantly we need to move/assign notes which are previously purchased and already existing in portfolios . That is the main objective which is achieved by lc.assign_to_portfolio.
Is that something that can be added or maybe a future development?

**Comment by ahartoto** [comment]
Unfortunately I'm not using `Folio`, so I'm not too familiar with what one would need on the secondary market.

On assigning previously purchased notes to existing portfolios: after reading the example that you had shown, it'd have to be done via HTTP session since it's not supported as part of an official API. So, that would require quite a bit of work.

**Comment by hdsouza** [comment]
Ok No problem Alex. Thank you for checking though.
Also I use Jeremy's script just to move notes. I buy Notes of the sec market using a PHP script. I use Powershell for all my heavy lifting and Winbatch is the brains, tying it all together :)
