### ISSUE TITLE
lendingclub2.loan.Loan.interest_rate() uses obsolete key (inRate vs. intRate)

### ISSUE THREAD

**Issue by zuser10** [ahartoto/lendingclub2#18]
Please note that lendingclub2.loan.Loan.interest_rate() is currently broken due to the following:
https://github.com/ahartoto/lendingclub2/blob/master/lendingclub2/loan.py
   line 258 should say 'intRate' instead of 'inRate'.
Reference:   https://www.lendingclub.com/developers/listed-loans

**Comment by ahartoto** [comment]
Thanks for reporting this!

**Comment by ahartoto** [comment]
BTW, do you need a release now?

**Comment by zuser10** [comment]
No hurry.  But thanks for the quick response and all your effort on the
project.

**Comment by ahartoto** [comment]
Forgot to mention that I released `0.5.2` yesterday.
